name: pre-commit
description: run pre-commit and optionally commit back to the pull request
inputs:
  token:
    description: github token to clone / push with
    required: false
  changed:
    description: only run against changed files in this commit.  requires unshallow checkout.
    required: true
    default: "false"
runs:
  using: "node12"
  main: "dist/index.js"
